import type { Metadata } from 'next';
import { Geologica } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import './globals.css';
import NavbarLayout from '@/components/layouts/navbar';
import FooterLayout from '@/components/layouts/footer';
import ReactQueryProvider from '@/providers/query-provider';

const geologica = Geologica({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geologica.className} antialiased`}>
        <ReactQueryProvider>
          <NavbarLayout />
          {children}
          <FooterLayout />
        </ReactQueryProvider>
      </body>
      <Toaster />
    </html>
  );
}
